spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
              default:
                key:
                 serde: org.apache.kafka.common.serialization.Serde$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serde$StringSerde
      bindings:
        event-in-0:
          destination: event

